# 🔥👌 littl

## A small, procedural/semi-functional language

Originally this language was written for a school assignment, now the reiterated version of it serves as a poc for Persephone. We have variables, which we can declare with either `var`, for mutable variables or `var!` for immutables and there is shorthand declaration with the `:=` operator (which doesn't require a var keyword). There are a couple of datatypes: `fun`, `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, `i64`, `f32`, `f64`, `bool` and `string`.

Littl also has C-style comparison and mathematical operators. Values can be returned with the `return` keyword.

=== Use it

```bash
git clone https://github.com/Azer0s/littl.git
cd littl
make
make run path/to/file
```

== Basic syntax

=== Functions

Declared like: `functionName(argument1 datatype,  argument2 datytpe...) return_type`

==== Example

```go

add(x u8, y u8) u16 {
    return x + y
}

```

=== Comparison

is, not | Equality

<,<=,>,>= | Greater/Smaller

=== For loops

Declared like: `for variable in array`

==== Example

```go
arr := {1,2,3,4,5}

for var i u8 in arr {
    print(i)
}

```

=== Counted for loops

Declared like: `for variableDeclaration; condition; operation`

==== Example

```go
arr := {1,2,3,4,5}

for var i u8 = 0; i < len(arr); i = i + 1{
    print(i)
}

for ;true; {
    console.log("Hello")
}

```


=== If condition

Declared like: `if condition`

Optional: `or if`

Optional: `else`

==== Example

```go
a := 5

if a < 10 {
    print("a is smaller than 10")
}
or if a > 21 {
    print("a is bigger than 21")
}
else{
    print("a is bigger than 10")
}

```

These statements have C-like blocks (curly brackets).

Since Littl transpiles to JavaScript, one can use JavaScript functions like `console.log`.

A recursive fibonacci sequence would look like so:

```go
fib(n u8) u32 {
    if n is 0 or n is 1 {
        return n
    }

    return fib(n-1) + fib(n-2)
}

x := fib(12)

print(x)
```

Littl also supports anonymous functions and currying
```go
curryAddition := anonymous(x u8) fun {
    return anonymous(y u8) u16 {
        return x + y
    }
}

var add3 fun

add3 = curryAddition(3)
print(add3(2))
```
